Metrics/MethodLength:
  Max: 15 # Adjust this number as needed

Layout/LineLength:
  Max: 198

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
